### ISSUE TITLE
Did the new discord update break it?

### ISSUE THREAD

**Issue by SheepCommander** [FC5570/powercord-message-hider#2]
![image](https://user-images.githubusercontent.com/66646514/148701524-78f1af4c-d657-433a-aadb-5570e1811829.png)

![image](https://user-images.githubusercontent.com/66646514/148701533-5b4944e7-2ba7-4eb5-a6c9-eb806c9ba5c2.png)

I thought it was working _yesterday_ but it doesn't seem to be working today

**Comment by FC5570** [comment]
I'll take a look. Looks like the new discord update seems to be the issue, yeah. They seem to have changed all the html class names.

**Comment by FC5570** [comment]
@SheepCommander Works for me. Try remounting the plugin by `powercord.pluginManager.remount('powercord-message-hider')`

**Comment by SheepCommander** [comment]
Thanks, that works
