### ISSUE TITLE
Doesn't seem to show up in message context menu

### ISSUE THREAD

**Issue by SheepCommander** [FC5570/powercord-message-hider#4]
![image](https://user-images.githubusercontent.com/66646514/165958410-6537afbf-1b35-4929-bd47-c18e64b8fe68.png)

**Comment by FC5570** [comment]
The context menu patching must have broken again. `powercord.pluginManager.remount('powercord-message-hider')` run this in console.

**Comment by SheepCommander** [comment]
VM1837:1 Uncaught ReferenceError: powercord is not defined
    at <anonymous>:1:1
(anonymous) @ VM1837:1

**Comment by FC5570** [comment]
I expected you to run that in "electron isolated" context. Read more about running powercord related code in console in the server.

**Comment by SheepCommander** [comment]
You mean Electron Isolated??
Anyways it works now
